### ISSUE TITLE
Restore Strudel

### ISSUE THREAD

**Issue by gogins** [gogins/cloud-music#19]
Bring Strudel back into cloud-music, but only as a Web resource, not as a submodule or a branch of Strudel. If possible. And it should be loaded from the Web server filesystem, not from a remote URL.

- [x] Implement stateful Patterns.
- [x] Template strings don't work in the REPL, replace them.
- [x] Get my `csoundn` Pattern to work from user code, or else patch `csound/index.mjs` with my code. _The `csoundn`pattern is now registered in `csoundac.mjs`._
- [x] Fix up `csoundac.mjs` to use stateful Patterns. _Added `eOP` and `O` for octavewise revoicing._
- [x] Fix sloppy timing. I _think_ I have done this.
- [x] Clean up diagnostics.
- [x] Clean up comments.
- [x] Create tests for all new Patterns. These can be Strudel patches that move through a sequence of Patterns.
- [x] Clean up documentation.
- [x] Log an issue with Strudel about Csound not working, with a pull request for a fix if possible. _No need, Csound is working again._
- [x] Log an [issue](https://github.com/tidalcycles/strudel/issues/658#:~:text=onTrigger%20pattern%20%23-,658,-Open) with Strudel about the non-dominant trigger in `csound` with a minimal working example. _This has been fixed by Roos._
- [x] Present the `StatefulPatterns` class with a minimal working example in the discussion about state. _Not doing this, as I can't actually get it to work._
- [x] Log an issue with Strudel about `pianoroll` not working with this stuff with a minimal working example. _Felix Roos explained this, I don't think this is easily solvable. It arises from the unpredictability of mixing the stateless chain of queries with stateful objects._

**Comment by gogins** [comment]
- [ ] Try Strudel again _on_ cloud-music.
- [ ] See about getting it on the server filesystem.
- [ ] If that works, do a piece to show it working.

**Comment by gogins** [comment]
OK, I got the updated-strudel branch working again locally.

So, my whole problem was in pnpm, not in Strudel. And that problem was fixed by reverting to the earlier LTS version of node.js.

Tomorrow I will try to come up with an intelligent question about integrating CsoundAC for Felix Roos.

I may also refactor the repository.

**Comment by gogins** [comment]
- [ ] Can I delete build artifacts and history from GitHub?

**Comment by gogins** [comment]
OK, I got this all wrong. I should be using `pnpm install` and Strudel's parts should be dependencies. I should _not_ be using a Git submodule. I will change my patching code to work in `node_modules/` and not in `strudel/packages/`. I will start a new branch to see if I can get that to work.

**Comment by gogins** [comment]
I need to patch `@strudel.cycles/website`.

**Comment by gogins** [comment]
On to scheduling CsoundAC things!

**Comment by gogins** [comment]
CsoundAC is not imported. However, I may simply need to drop my replacement for the Strudel embedded REPL, as with the imports it may now work.

**Comment by gogins** [comment]
OK, it's all working as a static module. I'm back to the original issue of scheduling haps.

**Comment by gogins** [comment]
A Hap context holds instance member variables; see the definition of `scaleTranspose` in `tonal.js`. That suggests my original design for `csoundac.mjs` is wrong, and should use the context.

**Comment by gogins** [comment]
Thanks. I'll have more questions....

**Comment by gogins** [comment]
I'm redoing `csoundac.mjs` one function at a time, starting with `chordN` and following the pattern of the native `scale` pattern.

**Comment by gogins** [comment]
Questions:

- [ ] Do I need to copy the CsoundAC objects by value before setting them in the Hap context?
- [ ] Can I insert the CsoundAC objects to the Hap value instead?
- [ ] If so, can they be objects, or must they be functions as the documentation states?

**Comment by gogins** [comment]
I think that the CsoundAC objects should be inserted using `hap.withValue()` in order to conform to functional programming idioms and prevent side effects.

**Comment by gogins** [comment]
Maybe my tired brain is beginning to grasp the whole idea. The Patterns are closures. The CsoundAC objects have to stay in the Pattern closures. When I look closely at the repeated evaluations, I see that they produce the same value.

**Comment by gogins** [comment]
This does the same thing as `csac.acG` and has the same problems:
```
const c = .988;
let y = .5;
const logistic = function() {
    let y1 = 4 * c * y * (1 - y);
    let midi_key = Math.round(y1 * 36 + 36);
    console.log('[logistic]: y: ' + y + ' y1: ' + y1 + '\n');
    console.log('[logistic]: midi_key: ' + midi_key + '\n');
    y = y1;
    return midi_key;
   };


pure().withValue(x => logistic())
 .note()
 .csoundm(6)
 .pianoroll({cycles:16,maxMidi:127,minMidi:0})
```

**Comment by gogins** [comment]
The current behavior is that one of the events in this pattern triggers a note, and then the `logistic` closure is evaluated for a whole bunch of other events. What I need is for the closure to be evaluated _only_ for the event that triggers a note. How can that be done?

**Comment by gogins** [comment]
More help, from @felixroos and @yaxu. I see their [solution](https://strudel.tidalcycles.org/?eCw7ehhFgi7X#d2luZG93LmNvdW50ID0gd2luZG93LmNvdW50IHx8IDQwOwp3aW5kb3cudXAgPSB3aW5kb3cudXAgPz8gdHJ1ZTsKCiJ4IHggW3hAMyB4XSIKICAud2l0aFZhbHVlKCh2KT0%2BewogICAgcmV0dXJuIHtub3RlOmNvdW50fTsKICB9KQogIC5vblRyaWdnZXIoKHQsIGhhcCk9PnsKICBjb25zb2xlLmxvZygndHJpZ2dlciB0aW1lJyxjb3VudCxoYXAudmFsdWUpCiAgICBpZihjb3VudCA%2BPSA4MCkgewogICAgICB3aW5kb3cudXAgPSBmYWxzZTsKICAgIH0gZWxzZSBpZihjb3VudCA8PSA0MCkgewogICAgICB3aW5kb3cudXAgPSB0cnVlCiAgICB9CiAgICBjb3VudCs9d2luZG93LnVwPzE6LTEKfSwgZmFsc2Up), but it is awkward.

1. Create state that is in scope of the necessary Patterns (their example does this in the window context).
2. in Pattern.onTrigger((t, hap) => {something}), modify that state when the event is triggered.
3. in Pattern.withValue, use that modified state to create the value.

This is excessively baroque. Possible ways to clean it up:

- [ ] Encapsulate this in my CsoundAC Patterns.
- [ ] Create a helper function that stuffs all this into a closure.

**Comment by felixroos** [comment]
> More help, from @felixroos and @yaxu. I see their solution, but it is awkward. [...] This is excessively baroque. 

It's not a solution, it's a workaround. Don't use state is the only real solution atm. If you have anything constructive to add to this, feel free to take part in this discussion: https://github.com/tidalcycles/strudel/discussions/646

**Comment by gogins** [comment]
I have been thinking about this for some time. I now have a much better understanding of onTrigger and withValue, so that should help.

I will try some things and get back to you if I come up with something constructive.

**Comment by gogins** [comment]
https://arxiv.org/abs/cs/0509027

**Comment by gogins** [comment]
Maybe I need to do something in the `Pattern.withValue` callback that is effectively the same as what generates a trigger.

**Comment by gogins** [comment]
I have attached a partially working example of a Pattern with state.
[stateful_pattern.txt](https://github.com/gogins/cloud-music/files/12008448/stateful_pattern.txt)

**Comment by gogins** [comment]
A `note` in Strudel seems to be a control, not (or in addition to being) a Pattern.

**Comment by gogins** [comment]
With `.note().piano()` the trigger is fired, with `.note().csoundm(6)` the trigger is not fired.

**Comment by gogins** [comment]
```
[statefulPattern][withValue] stateful.value: 71
VM6248:21 [statefulPattern][withValue] hap: {"whole":{"begin":{"s":1,"n":18,"d":1},"end":{"s":1,"n":19,"d":1}},"part":{"begin":{"s":1,"n":181,"d":10},"end":{"s":1,"n":91,"d":5}},"value":0,"context":{},"stateful":false}
VM6248:12 [Logistic.evaluate] y:  0.9674156519584135  y1:  0.12356862455282172  midi_key:  40
VM6248:24 [statefulPattern][onTrigger] time: 80.3885 
hap: {"whole":{"begin":{"s":1,"n":9,"d":1},"end":{"s":1,"n":19,"d":2}},"part":{"begin":{"s":1,"n":9,"d":1},"end":{"s":1,"n":181,"d":20}},"value":{"note":71,"clip":1,"s":"piano","release":0.1,"pan":0.5787037037037037},"context":{"dominantTrigger":false,"locations":[]},"stateful":false}
VM6248:20 [statefulPattern][withValue] stateful.value: 40
VM6248:21 [statefulPattern][withValue] hap: {"whole":{"begin":{"s":1,"n":17,"d":1},"end":{"s":1,"n":18,"d":1}},"part":{"begin":{"s":1,"n":2204,"d":125},"end":{"s":1,"n":8839,"d":500}},"value":0,"context":{},"stateful":false}
VM6248:20 [statefulPattern][withValue] stateful.value: 40
```

**Comment by gogins** [comment]
For Fractions, 's' is sign, 'n' is numerator, 'd' is denominator. Is sign here always 1?

**Comment by gogins** [comment]
This is the implementation of `fast` and, inverted, `slow`:
```
export const { fast, density } = register(['fast', 'density'], function (factor, pat) {
  if (factor === 0) {
    return silence;
  }
  factor = Fraction(factor);
  const fastQuery = pat.withQueryTime((t) => t.mul(factor));
  return fastQuery.withHapTime((t) => t.div(factor));
});
```

**Comment by gogins** [comment]
Can't seem to avoid "false triggers" if I do not register an onTrigger, but if I register an onTrigger then csoundm is not triggered.

Maybe I can register two patterns, always chaining the evaluation to the trigger.

**Comment by gogins** [comment]
I have proved that setting `onTrigger`, and emulating `onTrigger`, both produce similar results in that the events for the stateful Pattern _do not_ line up with the `csoundm` events.

**Comment by gogins** [comment]
Here is the implementation of Pattern.onTrigger from the runtime:
```
    onTrigger(s, o=!0) {
        return this.withHap(a=>a.setContext({
            ...a.context,
            onTrigger: (...f)=>{
                !o && a.context.onTrigger && a.context.onTrigger(...f),
                s(...f)
            }
            ,
            dominantTrigger: o
        }))
    }
```

**Comment by gogins** [comment]
This has been tedious indeed.

- [ ] All along, I have been able to pass stateful objects into Pattern functions and they are properly called. But they are not scheduled on triggers, rather they are of course scheduled on clock ticks (20 per second).
- [ ] Scheduling stateful objects in an `onTrigger` Pattern works for the default output, but not for the Csound outputs. Perhaps the `csound` outputs are not wired into the default output.- [ ] Finish the `registerStatefulValue` function.
- [ ] Finish as much of the `registerStatefulTrigger` function as I can.
- [ ] Consult with the Strudel developers about the trigger business.
- [ ] Also look for another solution or workaround.

**Comment by gogins** [comment]
The `stateful_pattern_3.html` test is the one I am focusing on now. It does not call `onTrigger` but does the same thing more or less. The thing works with the `piano` output but not with the `csoundm` output. I will have to take a closer look at that.

**Comment by gogins** [comment]
Got `csoundm` to work by using `note` in the value. But then the default sound is heard.

**Comment by gogins** [comment]
There is a `Pattern.prototype.n` that I _think_ is `note` but I have no idea where it is actually defined or how it actually works.

**Comment by gogins** [comment]
I'm now trying to define a `csounds` sound like the synth sounds. But it has to not tie into the WebAudio graph and yet still be triggered.

**Comment by gogins** [comment]
There may be a solution for `pianoroll` in this code that computes the colors of notes:
```
     const color = event.value?.color || event.context?.color;
      ctx.fillStyle = color || inactive;
      ctx.strokeStyle = color || active;
      ctx.globalAlpha = event.context.velocity ?? event.value?.gain ?? 1;
```
If I add `velocity` to the Hap.context that might do the job.

**Comment by gogins** [comment]
I have proved, that, indeed template strings cannot be used in code run from the REPL:
```
let msg = "Hello, world!";
let text = `This is a template string with: ${msg}`;
console.log("Text:", text);
pure(1)
```
That produces this error:
```
[eval] error: Expected number but "\"" found.
```

**Comment by gogins** [comment]
Should I try inversion of control?

**Comment by gogins** [comment]
The `acCN` pattern is receiving a Hap without a pitch value:
```
[csac][StatefulPatterns.registerMethods][onTrigger]:{
    "t": 8.968404988662131,
    "hap": {
        "whole": {
            "begin": {
                "s": 1,
                "n": 0,
                "d": 1
            },
            "end": {
                "s": 1,
                "n": 1,
                "d": 2
            }
        },
        "part": {
            "begin": {
                "s": 1,
                "n": 0,
                "d": 1
            },
            "end": {
                "s": 1,
                "n": 1,
                "d": 20
            }
        },
        "value": {
            "s": "sine",
            "gain": 0
        },
        "context": {
            "locations": [
                {
                    "start": 1777,
                    "end": 1778
                }
            ],
            "dominantTrigger": false
        },
        "stateful": false
    },
    "duration": 8.858412698412698,
    "cps": 1,
    "instance": {
        "ac_chord": {},
        "ac_modality": {},
        "current_time": 8.840997732426304
    }
}
```
I obviously need to understand how this happens.

**Comment by gogins** [comment]
There are no source maps, so much for understanding how it works except by reading the code. Which I did some more of, causing me to scotch the idea of calling the stateful pattern evaluator in the same way as the note trigger is called, because the later takes advantage of WebAudio timing and waits for the correct time to fire the trigger, which in my context I cannot do.

**Comment by gogins** [comment]
By the way, the built-in Csound in the regular Strudel REPL has quit working. My Csound works but only if I send the note on to a quiet `sound`. I seems that perhaps there is no actual trigger that does not come from scheduling a `sound` with WebAudio. There should be a dummy for this.

**Comment by gogins** [comment]
OK, I got it to work. The key was to distinguish between computations of state, which happen on cycle onsets and return the value of the state, from computations of Hap values, which happen on every query and may use the value of the state.

**Comment by gogins** [comment]
Still trouble with chaining values.

I have proved that setting the trigger to dominant in `stateful_patterns_experiment_1.html` causes it to fail, setting it to non-dominant allows it work.

**Comment by gogins** [comment]
One thing that is still messed up is I need `class.method(...args) ` to patternify changes of state, and I need `class.method(...args, value) to use state to assign or modify values.

**Comment by gogins** [comment]
Problem: how to register Patterns in a completely automatic way but with different methods for onsets and values.

- [ ] Registering pattern `PAT` will invoke `PAT_onTrigger` to compute state on every cycle onset and `PAT_withValue` to compute values on every query.
- [ ] Registering pattern `PAT` with invoke class method `PAT` both to compute state on every cycle onset and to compute values on every query. If the `hap` argument is `null` the state is computed, otherwise the value is computed.
- [ ] Registering pattern `PAT` with invoke class method `PAT` both to compute state on every cycle onset and to compute values on every query. If the `onset` argument is `true` the state is computed, otherwise the value is computed.
- [ ] The registration function will generate code somehow?

**Comment by gogins** [comment]
All triggers are firing, and all queries and returning values. However, it's still not working. The problem seems to be that the first Pattern that is triggered gets its note played, and the note produced further down the chain is ignored.

**Comment by gogins** [comment]
Improve diagnostics such that breaking on the Csound note will show note values going all the way back up the chain.

**Comment by gogins** [comment]
I need to change from `value` to `hap` in StatefulPatterns and class methods, because Strudel sometimes uses a primitive type and sometimes an object for values.

**Comment by gogins** [comment]
Still no help. Now trying to chain onTrigger.withValue instead of withValue.onTrigger.

**Comment by gogins** [comment]
Might finally be getting somewhere, but could again be a false alarm. Anyway this seems to work:
```
pure(0)
    .Logistic(logisticInstance, .995)
    .note()
    .fast(8)
    .acC(chordPattern, "GM C#M GM9 Am9 D7b9".slow(40))
    .acCT(chordPattern, "-1 1".slow(10))
    .acCV(chordPattern)
    .csoundn("6")
```
but this does not seem to work:
```
pure(0)
    .Logistic(logisticInstance, .995)
    .fast(8)
    .acC(chordPattern, "GM C#M GM9 Am9 D7b9".slow(40))
    .acCT(chordPattern, "-1 1".slow(10))
    .acCV(chordPattern)
    .note()
    .csoundn("6")
```

**Comment by gogins** [comment]
I am registering new Patterns but not exporting the Pattern functions. Is it possible to do e.g. `Pattern.acCK()`?

**Comment by gogins** [comment]
Faking the export of the new Patterns works, and appears to be required, to enable use of `every`, `apply`, and whatnot.

**Comment by gogins** [comment]
I am now patching Strudel as suggested by Felix Roos, in the `pattern.mjs` file. This seems to work without screwing up existing pieces.

**Comment by gogins** [comment]
The `pianoroll` works with my MWEs, but not with my actual pieces. I will investigate this.

**Comment by gogins** [comment]
I'm going nuts. Messing with my Strudel patches that do show a piano roll and trigger with `note`, I see that monkeying with the hap value makes the piano roll flatten out and, I suspect, messes up the behavior of `note.` I need to debug with a complete dump of the haps in both cases.

**Comment by gogins** [comment]
It seems there is a bass offset pushing my logistic notes way too high...

**Comment by gogins** [comment]
The native Strudel scale insists on having an actual bass _note_, not a root _pitch-class_. This pushes logistic notes up out of range.

**Comment by gogins** [comment]
Try fooling with the types of notes that go into the pianoroll.

**Comment by gogins** [comment]
OK, perhaps the problem is that the pianoroll only envisions one trigger for each note. In my code, there is more than one trigger that fires for each note. It seems to sound correct, but it does not display correctly. Rather, the inner pattern is displayed, but then the whole inner pattern jumps up and down in pitch according to the outer pattern.

**Comment by gogins** [comment]
I will redo my tests to verify the correctness of my Patterns... unambiguously.

**Comment by gogins** [comment]
Perhaps Haps are identified earlier or later than needed as notes.

**Comment by gogins** [comment]
This is not yet working and I have spent a lot of time on it. I suspect there is a lot of ad hoc design in Strudel. I am going to make one more attempt to get CsoundAC working in Strudel. I will not use the StatefulPatterns class, but the `.onTrigger(...).withHap(...)` pattern.

**Comment by gogins** [comment]
OK, more hints from Felix Roos and a little more understanding.

Unless state is dereferenced only in a stateless way, if I may, that is, based only on information in the haps, this cannot be done.

And the trouble that I saw before is, that `hasOnset` returns true more times than I would expect as compared to the `onTrigger` firing.

**Comment by gogins** [comment]
I can't see how to get the right information off the stack, i.e. in a stateless way, regarding cycle onsets. And there is still a problem with the default output lining up haps better than the Csound outputs.

So, I'm setting this aside for now.

**Comment by gogins** [comment]
Not fixable based on what I currently know. If there is one remaining question, it is whether it is possible to detect the _composer's_ cycle onset from changes of, or new, onsets created by Strudel while running.
